fixed the weather update bug

diff --git a/.local/bin/statusbar/weather b/.local/bin/statusbar/weather
--- a/.local/bin/statusbar/weather
+++ b/.local/bin/statusbar/weather
@@ -6,13 +6,21 @@ weatherreport="$HOME/.local/share/weatherreport"
 error() {
   echo "🌈 Weather error"
   rm -f "$weatherreport"
-  notify-send "🌈 Weather error" "$1"
+  notify-send "🌈 Weather error ($1)" "$2"
   exit
 }
 
 getforecast() {
-  errors="$( { ping -q -c 1 -W 1 8.8.8.8 >/dev/null; } 2>&1 )" || error "$errors"
-  errors="$( { curl -s "wttr.in/$location" > "$weatherreport"; } 2>&1 )" || error "$errors"
+  reason="curl"
+  if errors="$( { ping -q -c 1 -W 1 8.8.8.8; } 2>&1 )"; then
+    errors=""
+  else
+    reason="ping"
+  fi
+  errors="$errors
+$( {
+    curl --no-progress-meter --fail "wttr.in/$location" > "$weatherreport";
+  } 2>&1 )" || error "$reason" "$errors"
 }
 
 showweather() {
